// client/components/form/input/index.vue
<template>
  <div>
    <div class="flex items-center justify-between">
      <label
        v-if="label.length > 0"
        :for="id"
        class="block text-sm font-medium leading-6 text-gray-900 dark:text-white"
        >{{ label }}</label
      >
      <div v-if="side_label !== null" class="text-sm">
        <NuxtLink
          v-if="side_label.href != null"
          :to="side_label.href"
          class="font-semibold text-indigo-600 hover:text-indigo-500 dark:text-indigo-400 dark:hover:text-indigo-300"
          >{{ side_label.label }}</NuxtLink
        >
        <span v-else class="leading-6 text-gray-500 dark:text-gray-400">
          {{ side_label.label }}
        </span>
      </div>
    </div>
    <div
      :class="[
        inside_label != null
          ? 'flex ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 dark:bg-white/5 dark:ring-white/10 dark:focus:ring-indigo-500'
          : '',
        'relative rounded-md shadow-sm',
      ]"
    >
      <div
        v-if="icon != null"
        class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3"
      >
        <component
          :is="icon()"
          class="h-5 w-5 text-gray-400"
          aria-hidden="true"
        />
      </div>
      <span
        v-if="inside_label != null"
        class="flex select-none items-center pl-3 text-gray-500 dark:text-gray-300 sm:text-sm"
        >{{ inside_label }}</span
      >
      <input
        v-bind="$attrs"
        @input="
          (e: Event) => {
            set_invalid_pattern_feedback();
            $emit('input', e);
          }
        "
        :id="id"
        :name="id"
        :type="type"
        :autocomplete="type"
        :minlength="minlength"
        :maxlength="maxlength"
        :required="required"
        :value="value"
        :class="[
          icon != null ? 'pl-10' : '',
          inside_label != null
            ? 'flex-1 bg-transparent pl-1 focus:ring-0'
            : 'w-full ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 dark:bg-white/5 dark:ring-white/10 dark:focus:ring-indigo-500',
          'block rounded-md border-0 py-1.5 text-gray-900 placeholder:text-gray-400 dark:text-white sm:text-sm sm:leading-6',
        ]"
        :placeholder="placeholder != null ? placeholder : ''"
        :pattern="pattern != null ? pattern : ''"
      />
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { EnvelopeIcon } from '@heroicons/vue/20/solid';

type SideLabel = {
  label: string;
  href: string | null;
};

export default defineComponent({
  name: 'FormInput',
  components: { EnvelopeIcon },
  methods: {
    set_invalid_pattern_feedback() {
      const input = document.getElementById(this.id) as HTMLInputElement;
      if (this.force_invalid_feedback || input.validity.patternMismatch) {
        input.setCustomValidity(this.invalid_pattern_feedback);
      } else input.setCustomValidity('');
    },
  },
  created() {
    watch(
      () => this.force_invalid_feedback,
      () => this.set_invalid_pattern_feedback(),
    );
  },
  props: {
    id: {
      type: String,
      required: true,
    },
    type: {
      type: String,
      required: true,
    },
    label: {
      type: String,
      default: '',
    },
    placeholder: {
      type: String,
      default: null,
    },
    icon: {
      type: Function,
      default: null,
    },
    required: {
      type: Boolean,
      default: false,
    },
    side_label: {
      type: Object as () => SideLabel,
      default: null,
    },
    inside_label: {
      type: String,
      default: null,
    },
    pattern: {
      type: String,
      default: '.*',
    },
    invalid_pattern_feedback: {
      type: String,
      default: null,
    },
    minlength: {
      type: Number,
      default: 0,
    },
    maxlength: {
      type: Number,
      default: 10000,
    },
    force_invalid_feedback: {
      type: Boolean,
      default: false,
    },
    value: {
      type: String,
      default: '',
    },
  },
  emits: {
    input: () => true,
  },
});
</script>

// src/lib/components/form/Input.svelte
<script lang="ts">
	import type { Component } from 'svelte';
	import type { HTMLInputAttributes } from 'svelte/elements';

	let {
		id,
		label = '',
		icon: Icon,
		invalidPatternFeedback,
		class: className = '',
		value = $bindable(''),
		...rest
	}: HTMLInputAttributes & {
		id: string;
		label?: string;
		icon?: Component<{ class?: string; 'aria-hidden'?: boolean | 'true' | 'false' }>;
		invalidPatternFeedback?: string;
		class?: string;
	} = $props();

	function validate(e: Event) {
		const input = e.currentTarget as HTMLInputElement;
		if (invalidPatternFeedback && input.validity.patternMismatch) {
			input.setCustomValidity(invalidPatternFeedback);
		} else input.setCustomValidity('');
	}
</script>

<div class={className}>
	{#if label}
		<label for={id} class="block text-sm leading-6 font-medium text-second-900 dark:text-white"
			>{label}</label
		>
	{/if}
	<div class="relative rounded-md shadow-sm">
		{#if Icon}
			<div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
				<Icon class="size-5 text-second-400" aria-hidden="true" />
			</div>
		{/if}
		<input
			{id}
			name={id}
			bind:value
			oninput={validate}
			{...rest}
			class="block w-full rounded-md border-0 py-1.5 text-second-900 ring-1 ring-gray-300 ring-inset placeholder:text-second-400 focus:ring-2 focus:ring-prime-600 focus:ring-inset sm:text-sm sm:leading-6 dark:bg-white/5 dark:text-white dark:ring-white/10 dark:focus:ring-prime-500 {Icon
				? 'pl-10'
				: ''}"
		/>
	</div>
</div>
